import { PinID } from '@/types/circuit';

export const generateArduinoCode = (ledPin: PinID, btnPin: PinID): string => {
  return `/*
  * Auto-Generated by HashLab Arduino Simulator
  * Task: LED Control via Push Button
  */

const int LED_PIN = ${ledPin};
const int BTN_PIN = ${btnPin};

void setup() {
  // Initialize Pins
  pinMode(LED_PIN, OUTPUT);
  pinMode(BTN_PIN, INPUT);
}

void loop() {
  // Read Button State
  int btnState = digitalRead(BTN_PIN);

  // Logic: Direct Control
  if (btnState == HIGH) {
    digitalWrite(LED_PIN, HIGH);
  } else {
    digitalWrite(LED_PIN, LOW);
  }
}
`;
};